### ISSUE TITLE
seed from crypto/rand, not timestamp

### ISSUE THREAD

**Issue by glycerine** [nats-io/nuid#1]
(Nice library!)

Re 

https://github.com/nats-io/nuid/blob/master/nuid.go#L49

I've had code reviews from ex-NSA guys who pointed out seeding with the current timestamp is actually pretty non-random, and is not too difficult to reverse engineer.

The alternative: it is simpler and more random to seed from crypto/rand instelf.

**Comment by mcqueary** [comment]
@glycerine Hi Jason. I think what you're raising is a valid point for a general-purpose UUID generator that might be used e.g. to generate a one-time password or key pair. That being said, I don't believe _any_ so-called UUID generator should be considered secure without some other layer of security on top of it.

In our case, NUID is designed to be an entropy-pool-friendly way to generate large volumes of random subject names and minimize the risk of name collision. I believe NUID meets that goal. Although the risk of a successful directed attack against an individual user (i.e. trying to crack an individual ephemeral INBOX name) is infinitesimally small, I would always apply some type of access and/or authorization control on top of NATS in general and the segment of the namespace in particular before worrying about inbox subject name cracking.

@derekcollison - any additional thoughts?

**Comment by derekcollison** [comment]
They better be totally unique.. ;)

We could seed with crypto data versus time, for the sequence seed and the sequence increment amount.
